/*Exp 4.- Write a program to generate a of random numbers between 1 and 6.
Hints for Solution - The random numbers may be generated by using method random of class
Math. The code may be written as:
randarray = (int)(10*Math.random()%6) +1; */


public class d {
    public static void main(String args[]){
        System.out.print("\n--------------------\n");
        int randarray = (int)(10*Math.random()%6) +1;
        System.out.println(" Random number are := "+randarray);
        System.out.print("-----------------------\n");
    }
}